# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculate_h <- function(omega, alpha, beta, gamma, returns, g0) {
    .Call('_CarrMidas_calculate_g', PACKAGE = 'CarrMidas', omega, alpha, beta, gamma, returns, g0)
}

sum_tau <- function(m, theta, phivar, covariate, K) {
    .Call('_CarrMidas_sum_tau', PACKAGE = 'CarrMidas', m, theta, phivar, covariate, K)
}

